services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
    ports:
      - "3306:3306"  # Exposing port 3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"  # Exposing phpMyAdmin on port 8090
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mysqlroot
      PMA_ARBITRARY: 1
    depends_on:
      - db

volumes:
  db_data: